import type { IFlight } from "../../types/flight.types";

export const FLIGHTS_DATA: IFlight[] = [
  {
    logo: "logos/turkish.svg",
    airline: "TK143",
    company: "Turkey",
    aircraftReg: "TC-JFP",
    id: 93247,
    departureTime: "2025-07-04T15:34:00",
    arrivalTime: "2025-07-04T15:34:20",
    from: {
      city: "Sofia",
      country: "Bulgaria",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "SOF",
    },
    to: {
      city: "Beijing",
      country: "China",
      countryCode: "CN",
      timezone: "UTC +8",
      code: "PEK",
    },
    airplane: {
      aviaCompany: "Turkish",
      image: "aircrafts/turkish.png",
      name: "Airbus A330",
      flag: "flags/turkey-flag.svg",
    },
    colorGradient: ["#ffdede", "#ffbaba"],
    route: {
      speed: 870,
      altitude: 10600,
    },
  },
  {
    logo: "logos/ryanair.svg",
    airline: "RN1782",
    aircraftReg: "D-AISP",
    company: "Ireland",
    id: 7842,
    departureTime: "2025-07-04T14:31:00",
    arrivalTime: "2025-07-04T14:31:30",
    from: {
      city: "Dublin",
      country: "Ireland",
      countryCode: "IE",
      timezone: "UTC +1",
      code: "DUB",
    },
    to: {
      city: "Larnaca",
      country: "Cyprus",
      countryCode: "CY",
      timezone: "UTC +3",
      code: "LCA",
    },
    airplane: {
      aviaCompany: "Rinair",
      image: "aircrafts/ryanair.png",
      name: "Boeing 737-800",
      flag: "flags/ireland-flag.svg",
    },
    colorGradient: ["#A1C6E1", "#88B5E0"],
    route: {
      speed: 840,
      altitude: 11200,
    },
  },
  {
    logo: "logos/s7.svg",
    airline: "S7124",
    aircraftReg: "RA-73415",
    company: "Russia",
    id: 88015,
    departureTime: "2025-07-04T14:31:00",
    arrivalTime: "2025-07-04T14:32:00",
    from: {
      city: "Nice",
      country: "France",
      countryCode: "FR",
      timezone: "UTC +2",
      code: "NCE",
    },
    to: {
      city: "Tbilisi",
      country: "Georgia",
      countryCode: "GE",
      timezone: "UTC +4",
      code: "TBS",
    },
    airplane: {
      aviaCompany: "S7",
      image: "aircrafts/s7.png",
      name: "Airbus A320neo",
      flag: "flags/russia-flag.svg",
    },
    colorGradient: ["#d6ffe5", "#96f2c1"],
    route: {
      speed: 860,
      altitude: 10900,
    },
  },
  {
    logo: "logos/swiss.svg",
    airline: "LX318",
    aircraftReg: "HB-JHK",
    company: "Switzerland",
    id: 94102,
    departureTime: "2025-07-04T11:00:00",
    arrivalTime: "2025-07-04T12:00:00",
    from: {
      city: "Porto",
      country: "Portugal",
      countryCode: "PT",
      timezone: "UTC +1",
      code: "OPO",
    },
    to: {
      city: "Baku",
      country: "Azerbaijan",
      countryCode: "AZ",
      timezone: "UTC +4",
      code: "GYD",
    },
    airplane: {
      aviaCompany: "NordWind",
      image: "aircrafts/swiss.png",
      name: "Airbus A220-300",
      flag: "flags/switzerland-flag.svg",
    },
    colorGradient: ["#e6e6ff", "#a8b4ff"],
    route: {
      speed: 830,
      altitude: 10700,
    },
  },
  {
    logo: "logos/lufthansa.svg",
    airline: "LH401",
    aircraftReg: "D-AIXD",
    company: "Germany",
    id: 90936,
    departureTime: "2025-07-04T12:20:00",
    arrivalTime: "2025-07-04T15:00:00",
    from: {
      city: "Burgas",
      country: "Bulgaria",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "BOJ",
    },
    to: {
      city: "Muscat",
      country: "Oman",
      countryCode: "OM",
      timezone: "UTC +4",
      code: "MCT",
    },
    airplane: {
      aviaCompany: "Lufthansa",
      image: "aircrafts/lufthansa.png",
      name: "Airbus A350-900",
      flag: "flags/germany-flag.svg",
    },
    colorGradient: ["#e5f2ff", "#9dd2f9"],
    route: {
      speed: 890,
      altitude: 11300,
    },
  },
  {
    logo: "logos/lufthansa.svg",
    airline: "LH401",
    aircraftReg: "D-AIXD",
    company: "Germany",
    id: 90931,
    departureTime: "2025-07-04T12:20:00",
    arrivalTime: "2025-07-04T15:00:00",
    from: {
      city: "Burgas",
      country: "France",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "BOJ",
    },
    to: {
      city: "Muscat",
      country: "Oman",
      countryCode: "OM",
      timezone: "UTC +4",
      code: "MCT",
    },
    airplane: {
      aviaCompany: "Lufthansa",
      image: "aircrafts/lufthansa.png",
      name: "Airbus A350-900",
      flag: "flags/germany-flag.svg",
    },
    colorGradient: ["#e5f2ff", "#9dd2f9"],
    route: {
      speed: 890,
      altitude: 11300,
    },
  },
  {
    logo: "logos/lufthansa.svg",
    airline: "LH401",
    aircraftReg: "D-AIXD",
    company: "Turkey",
    id: 90930,
    departureTime: "2025-07-04T12:20:00",
    arrivalTime: "2025-07-04T15:00:00",
    from: {
      city: "Burgas",
      country: "France",
      countryCode: "BG",
      timezone: "UTC +3",
      code: "BOJ",
    },
    to: {
      city: "Muscat",
      country: "Oman",
      countryCode: "OM",
      timezone: "UTC +4",
      code: "MCT",
    },
    airplane: {
      aviaCompany: "Turkish",
      image: "aircrafts/turkish.png",
      name: "Airbus A330",
      flag: "flags/turkey-flag.svg",
    },
    colorGradient: ["#e5f2ff", "#9dd2f9"],
    route: {
      speed: 890,
      altitude: 11300,
    },
  },
];
